### ISSUE TITLE
Can't add description to .jpg files

### ISSUE THREAD

**Issue by b2u0s5** [martinlb/PrettyIndex#1]
When I try to add a description to .jpg files (`AddDescription "Image" *.jpg`) it show an error 500.

**Comment by martinlb** [comment]
I don't have this issue.
When I add the following line (`AddDescription "Image" *.jpg` ) at the end of my descriptions section, everything works fine :
![image](https://user-images.githubusercontent.com/3133757/69247793-531dda80-0bab-11ea-890a-6f41031f4b94.png)

I think it comes from your apache conf.

Did you try to make a minimal .htaccess file with only the autoindex and the description for JPG?
